language: php
php:
  - 7.0
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - "composer install"
script: 
  - "vendor/bin/selenium-server-standalone &"
  - sleep 3 #give selenium server time to start
  - "vendor/bin/phpunit test.php"
