language: php
php:
  - 7.0
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - "composer install"
script: 
  - "vendor/bin/selenium-server-standalone &"
  - sleep 3 #give selenium server time to start
  - "vendor/bin/phpunit test.php"
