language: php
php:
  - 7.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - "composer install"
script: 
  - "vendor/bin/selenium-server-standalone &"
  - sleep 3 #give selenium server time to start
  - "vendor/bin/phpunit test.php"
